server.port=8095

# DataSource SQLite
spring.datasource.url=jdbc:sqlite:./database/bd_tp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Desactivar consola H2
spring.h2.console.enabled=false

# Inicializaci?n de datos (comentado para evitar conflictos)
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:rutas_db.sql
