server.port=8095

# Conexion al microservicio de Transporte/Camiones (nombre del contenedor)
api.camiones.base-url=http://ms-transporte:8085/api/camiones

# DataSource PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Desactivar consola H2
spring.h2.console.enabled=false

# KEYCLOAK con nombre de contenedor
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://host.docker.internal:8081/realms/bda-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.docker.internal:8081/realms/bda-realm/protocol/openid-connect/certs

# ====================================
# CONFIGURACIÓN DE SWAGGER/OPENAPI
# ====================================
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
