spring.application.name=microservicio-solicitudes
server.port=8090

# conexion rutas (CORREGIDO: 8095 es el puerto real de ms-Rutas)
api.rutas.base-url=http://localhost:8095/api/rutas

# DataSource SQLite
spring.datasource.url=jdbc:sqlite:./database/bd_tp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA - NO tocar la estructura, solo validar
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Desactivar consola H2
spring.h2.console.enabled=false

# Inicialización de datos
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:solicitud_data.sql
spring.sql.init.continue-on-error=true
