spring.application.name=microservicio-solicitudes
server.port=8090

# conexion rutas (Para Docker usar nombre del contenedor)
api.rutas.base-url=http://localhost:8095/api/rutas

# DataSource SQLite
spring.datasource.url=jdbc:sqlite:./database/bd_tp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA - NO tocar la estructura, solo validar
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Desactivar consola H2
spring.h2.console.enabled=false

# Inicializaci?n de datos - DESACTIVADA (ya que no existen los archivos .sql)
spring.sql.init.mode=never

# ====================================
# ? CONFIGURACIÓN DE KEYCLOAK
# ====================================

# URL del servidor Keycloak (issuer)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/bda-realm

# JWK Set URI para validar tokens JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/bda-realm/protocol/openid-connect/certs


# Habilitar logs para debugging (opcional)
logging.level.org.springframework.security=DEBUG
