spring.application.name=transportes

# ==============================

# Puerto del servidor
server.port=8085

# Configuraci?n de la base de datos SQLite
spring.datasource.url=jdbc:sqlite:./database/bd_tp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Desactivar la consola web de H2
spring.h2.console.enabled=false

# ====================================
# CONFIGURACIÓN DE KEYCLOAK (Resource Server JWT)
# ====================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/bda-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/bda-realm/protocol/openid-connect/certs

# Logs de seguridad para debugging (opcional)
logging.level.org.springframework.security=DEBUG

# ====================================
# CONFIGURACIÓN DE SWAGGER/OPENAPI
# ====================================
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
