spring.security.oauth2.resourceserver.jwt.issuer-uri=http://host.docker.internal:8081/realms/bda-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.docker.internal:8081/realms/bda-realm/protocol/openid-connect/certs

# Logs de seguridad para debugging
logging.level.org.springframework.security=DEBUG
spring.application.name=transportes

# Puerto del servidor
server.port=8085

# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Desactivar la consola web de H2
spring.h2.console.enabled=false
