spring.application.name=transportes

# ==============================

# Puerto del servidor
server.port=8085

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sqAdmin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# JPA - PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Desactivar la consola web de H2
spring.h2.console.enabled=false

# ====================================
# CONFIGURACIÓN DE KEYCLOAK (Resource Server JWT)
# ====================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/bda-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/bda-realm/protocol/openid-connect/certs

# Logs de seguridad para debugging (opcional)
logging.level.org.springframework.security=DEBUG
