spring.application.name=Gateway
server.port=8080

# Direcciones de los microservicios para Docker (usar nombres de contenedores)
uri.ms-rutas=http://ms_rutas:8095
uri.ms-solicitudes=http://ms_solicitudes:8090
uri.ms-camiones=http://ms_transporte:8085

