spring.application.name=gateway
server.port=8080

# ======================================
# URIs de Microservicios
# ======================================
uri.ms-rutas=http://localhost:8095
uri.ms-solicitudes=http://localhost:8090
uri.ms-camiones=http://localhost:8085
uri.ms-tarifas=http://localhost:8092

# ======================================
# PATHS DE CADA MICROSERVICIO
# (estos los usa el Gateway)
# ======================================

# Microservicio RUTAS
paths.ms-rutas=/api/rutas/**,\
               /api/tramos/**,\
               /api/depositos/**,\
               /api/ciudades/**,\
               /api/osrm/**,\
               /api/tipos-tramo/**,\
               /api/estados-tramo/**

# Microservicio SOLICITUDES
paths.ms-solicitudes=/api/solicitudes/**,\
                     /api/contenedores/**,\
                     /api/clientes/**

# Microservicio CAMIONES
paths.ms-camiones=/api/camiones/**,\
                  /api/transportistas/**

# Microservicio TARIFAS
paths.ms-tarifas=/api/tarifas/**,\
                 /api/config/**
