spring.application.name=Gateway
server.port=8080

# Direcciones de los microservicios (CORREGIDAS)
uri.ms-rutas=http://localhost:8095
uri.ms-solicitudes=http://localhost:8090
uri.ms-camiones=http://localhost:8085
