server.port=8095

# Conexi?n al microservicio de Transporte/Camiones
api.camiones.base-url=http://localhost:8085/api/camiones

# DataSource SQLite
spring.datasource.url=jdbc:sqlite:./database/bd_tp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Desactivar consola H2
spring.h2.console.enabled=false

# Google Maps API Configuration
google.maps.api.base-url=https://maps.googleapis.com/maps/api
google.maps.api.key=AIzaSyBaZAb5gL8qGaW15bXfDShxTlpaHVDqPjY

# ====================================
# CONFIGURACIÓN DE KEYCLOAK (Resource Server JWT)
# ====================================
# Ajusta la URL del issuer a la de tu Keycloak (mismo realm que uses en el proyecto)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/bda-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/bda-realm/protocol/openid-connect/certs

# Logs de seguridad para debugging (opcional)
logging.level.org.springframework.security=DEBUG
