# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/proper_basedatostp
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# Inicialización con SQL personalizado
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/base.sql

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
