spring.application.name=gateway
server.port=8080

# ======================================
# URIs de Microservicios (nombres de contenedores Docker)
# ======================================
uri.ms-rutas=http://ms-rutas:8095
uri.ms-solicitudes=http://ms-solicitudes:8090
uri.ms-camiones=http://ms-transporte:8085

# ======================================
# PATHS DE CADA MICROSERVICIO
# ======================================

# Microservicio RUTAS
paths.ms-rutas=/api/rutas/**,\
               /api/tramos/**,\
               /api/depositos/**,\
               /api/ciudades/**,\
               /api/osrm/**,\
               /api/tipos-tramo/**,\
               /api/estados-tramo/**

# Microservicio SOLICITUDES
paths.ms-solicitudes=/api/solicitudes/**,\
                     /api/contenedores/**,\
                     /api/clientes/**

# Microservicio CAMIONES/TRANSPORTES
paths.ms-camiones=/api/camiones/**,\
                  /api/transportistas/**

# ======================================
# KEYCLOAK OAuth2 Resource Server (Docker)
# ======================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://host.docker.internal:8081/realms/bda-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.docker.internal:8081/realms/bda-realm/protocol/openid-connect/certs

# Logs de seguridad
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
