spring.application.name=gateway
server.port=8080

# ======================================
# URIs de Microservicios (nombres de contenedores Docker)
# ======================================
uri.ms-rutas=http://ms-rutas:8095
uri.ms-solicitudes=http://ms-solicitudes:8090
uri.ms-camiones=http://ms-transporte:8085

# ======================================
# PATHS DE CADA MICROSERVICIO
# ======================================

# Microservicio RUTAS
paths.ms-rutas=/api/rutas/**,\
               /api/tramos/**,\
               /api/depositos/**,\
               /api/ciudades/**,\
               /api/osrm/**,\
               /api/tipos-tramo/**,\
               /api/estados-tramo/**

# Microservicio SOLICITUDES
paths.ms-solicitudes=/api/solicitudes/**,\
                     /api/contenedores/**,\
                     /api/clientes/**

# Microservicio CAMIONES
paths.ms-camiones=/api/camiones/**,\
                  /api/transportistas/**

