spring.application.name=Gateway
server.port=8080

# Direcciones de los microservicios
uri.ms-rutas=http://localhost:8081
uri.ms-solicitudes=http://localhost:8082
uri.ms-camiones=http://localhost:8083
