spring.application.name=transportes

# ==============================

# Puerto del servidor
server.port=8085

# Configuración de la base de datos SQLite
spring.datasource.url=jdbc:sqlite:./database/bd_tp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Desactivar la consola web de H2
spring.h2.console.enabled=false
