-- schema.sql (PostgreSQL)

-- TABLAS AUXILIARES
CREATE TABLE ciudad (
                        id_ciudad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre varchar(100) NOT NULL
);

CREATE TABLE tipo_tramo (
                            id_tipo_tramo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nombre varchar(100) NOT NULL
);

CREATE TABLE estado_tramo (
                              id_estado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name varchar(50) NOT NULL
);

CREATE TABLE estado_solicitud (
                                  id_estado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name varchar(50) NOT NULL
);

-- ENTIDADES PRINCIPALES
CREATE TABLE cliente (
                         id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nombre varchar(100) NOT NULL,
                         apellido varchar(100),
                         dni varchar(20),
                         telefono varchar(30),
                         mail varchar(120),
                         direccion varchar(200)
);

CREATE TABLE contenedor (
                            id_contenedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            peso numeric(10,2),
                            volumen numeric(10,2)
);

CREATE TABLE deposito (
                          id_deposito integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre varchar(150),
                          direccion varchar(250),
                          latitud numeric(10,6),
                          longitud numeric(10,6),
                          costo_estadia_diario numeric(10,2),
                          id_contenedor integer REFERENCES contenedor(id_contenedor),
                          id_ciudad integer REFERENCES ciudad(id_ciudad)
);

CREATE TABLE transportista (
                               id_transportista integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               nombre varchar(150),
                               telefono varchar(30),
                               mail varchar(120),
                               direccion varchar(250)
);

CREATE TABLE camiones (
                          id_camion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          patente varchar(20) NOT NULL,
                          id_transportista integer REFERENCES transportista(id_transportista),
                          telefono varchar(30),
                          capacidad_peso numeric(10,2),
                          capacidad_volumen numeric(10,2),
                          disponibilidad boolean DEFAULT true,
                          costos jsonb,
                          costo_base_km numeric(10,2),
                          consumo_combustible_km numeric(10,3)
);

CREATE TABLE tramo (
                       id_tramo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       latitud_origen numeric(10,6),
                       longitud_origen numeric(10,6),
                       latitud_destino numeric(10,6),
                       longitud_destino numeric(10,6),
                       costo_aproximado numeric(12,2),
                       costo_real numeric(12,2),
                       fechaHoraInicio timestamp,
                       fechaHoraFin timestamp,
                       id_camion integer REFERENCES camiones(id_camion),
                       id_tipoTramo integer REFERENCES tipo_tramo(id_tipo_tramo),
                       id_estado integer REFERENCES estado_tramo(id_estado),
                       id_ruta integer, -- FK se agrega después si se crea ruta primero
                       id_deposito_origen integer REFERENCES deposito(id_deposito),
                       id_deposito_destino integer REFERENCES deposito(id_deposito)
);

CREATE TABLE ruta (
                      id_ruta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      id_solicitud integer, -- FK a solicitud (se define después)
                      cantidadTramos integer,
                      cantidadDepositos integer,
                      id_tramo integer REFERENCES tramo(id_tramo)
);

CREATE TABLE tarifa_parcial (
                                nro_tarifa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                costo_por_km numeric(10,4),
                                valor_litro_combustible numeric(10,4),
                                costo_estadia_deposito numeric(12,2),
                                cargo_gestion_por_tramo numeric(12,2),
                                fecha_emision date,
                                fecha_vigencia date
);

CREATE TABLE tarifa_final (
                              nro_tarifa integer PRIMARY KEY,
                              tarifa_parcial integer REFERENCES tarifa_parcial(nro_tarifa),
                              costo_combustible_total numeric(12,2),
                              costo_estadia_total numeric(12,2),
                              tiempo_real interval,
                              costo_total_real numeric(12,2),
                              fecha_calculo timestamp
);

CREATE TABLE solicitud (
                           numero_solicitud integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           id_contenedor integer REFERENCES contenedor(id_contenedor),
                           id_cliente integer REFERENCES cliente(id_cliente),
                           costo_estimado numeric(12,2),
                           tiempo_estimado interval,
                           costo_final numeric(12,2),
                           tiempo_real interval,
                           id_tarifa integer REFERENCES tarifa_final(nro_tarifa),
                           estado_solicitud integer REFERENCES estado_solicitud(id_estado)
);

-- REPARAR FK que referencian entre tablas ya creadas
ALTER TABLE tramo
    ADD CONSTRAINT fk_tramo_ruta
        FOREIGN KEY (id_ruta) REFERENCES ruta(id_ruta);

ALTER TABLE ruta
    ADD CONSTRAINT fk_ruta_solicitud
        FOREIGN KEY (id_solicitud) REFERENCES solicitud(numero_solicitud);
