version: "3.9"

services:
  ms-rutas:
    build: ./ms-Rutas
    container_name: ms_rutas
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
    networks:
      [app-network]

  ms-solicitudes:
    build: ./ms-Solicitudes
    container_name: ms_solicitudes
    image: postgres
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - ms-rutas
    volumes:
      -

  ms-transporte:
    build: ./ms-Transporte
    container_name: ms_transporte
    ports:
      - "8095:8095"

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - ms-rutas
      - ms-solicitudes
      - ms-transporte

networks:
  app-net:
    driver: bridge